// <auto-generated by="the Blazor I18n Text compiler" />
namespace Benriya.Clients.Wasm.Components.I18nText
{
    public partial class Manager : global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage, global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextLateBinding
    {
        string global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage.FallBackLanguage => "en";

        public string this[string key] => global::Toolbelt.Blazor.I18nText.I18nTextExtensions.GetFieldValue(this, key);

        /// <summary>"Add new"</summary>
        public string AddNew;

        /// <summary>"Azure"</summary>
        public string Azure;

        /// <summary>"Edit"</summary>
        public string Edit;
    }
}
